# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a33e585a5afcbff1cb5694b83dc35e9847671640104e27685ad1bb1bf460aab1674c80ce6d0116a21db7c8feffc8d99a7d67ed1adbdc5b2a16e22b4cce9160e

test:
  secret_key_base: e808ff23a3f1c1bd21c0d73892932e57fc8afade53d1b33b4d095ed7bb87b9c60dae84dcbb5a427e86438e115dc1cfeb485d9fe49d61ac498ce424f462eaf5b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
